### ISSUE TITLE
Translate README and installation instructions to Bengali

### ISSUE THREAD

**Issue by ChimeraCoder** [ChimeraCoder/koro#1]
Currently, the README (which contains the installation instructions) are all in English. We should provide these in Bengali as well.

**Comment by ranamahmud** [comment]
I want to translate the README in Bengali.

**Comment by ChimeraCoder** [comment]
@ranamahmud Please do! We'd love to have the rest of the README translated. :)

**Comment by meAbab** [comment]
Hi, 
I've translated the current README here - https://github.com/meAbab/koro/blob/master/README.md. If it suits please update with master.
Thanks.

**Comment by ChimeraCoder** [comment]
@meAbab Thanks!


Could you submit a pull request, and also [enable contributions from maintainers](https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/), so that I can make a couple of formatting changes to it before merging?
